services:
  - type: web
    name: fuelops-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx tsc
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
